name: NuGet Sources
description: Configures NuGet package sources by installing a NuGet.Config file
inputs:
  destination:
    description: Destination directory for the NuGet.Config file
    required: true
    default: '.'
runs:
  using: composite
  steps:
    - shell: bash
      run: cp "${{ github.action_path }}/NuGet.Config" "${{ inputs.destination }}"
